import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

const satoshi = localFont({
  src: [
    {
      path: '../public/fonts/Satoshi/Satoshi-Variable.woff2',
      style: 'normal',
    },
    {
      path: '../public/fonts/Satoshi/Satoshi-VariableItalic.woff2',
      style: 'italic',
    },
  ],
  variable: '--font-satoshi',
});

const theSeasons = localFont({
  src: [
    {
      path: '../public/fonts/TheSeasons/TheSeasons-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/TheSeasons/TheSeasons-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/TheSeasons/TheSeasons-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-the-seasons',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.variable} ${theSeasons.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
